QUESTION_ZERO = "DID YOU SETUP ALL DEPENDENCIES AND PUT YOUR PROJECT TO THE APPROPRIATE PLACE?\n\
        HINT: the project root should be in the same level as this main.py. If you skip or mistake\n\
        this step, the following steps may not work. Please confirm (Y/N)"

QUESTION_ONE = "What is your context of this project? Usually, We expect to have a short\n\
        description of the project, and the main goal you want to achieve.\n\
            Please answer in one or two sentences.\n\
        also, kindly provide a brief description of the dataset you are using if you have one."

QUESTION_TWO = "Which prober do you want to use? Please choose from the following options: (1 to 10)"

QUESTION_THREE = "Which development document generated by our agent do you want to use?\n\
        Please choose from the following options: (1 to 3)"

QUESTION_FOUR = "For iterative improvement, how many iterations do you want to run?\n\
    please input a positive integer. If you just press enter, we will run 3 iterations in normal mode\n\
    or 10 iterations in auto-research mode."

QUESTION_FIVE = "Now agent finished the work, do you want to try another prober or exit? Please answer Y/N"

QUESTION_SIX = "Do you want to use the auto-research feature? The agent will read your probe\n\
        and annotate train.py with 10 targeted improvement suggestions before iterating. (Y/N, default N)"

QUESTION_SEVEN = "Do you want to manually override the probe threshold for this run? (Y/N, default N)\n\
        If yes, you will be prompted for a new threshold value, and the override will be applied\n\
        everywhere it is referenced (dev plan JSON, prober.py, and existing probe_result_*.json status)."

QUESTION_SEVEN_VALUE = "Enter the new threshold (use the same wording as the dev plan, e.g. '0.15',\n\
        '< 0.03', or 'AUROC degradation < 0.05'):"
